[[session]]
name = "scratch"
path = "~"

[[session]]
name = "alon-mbp ğŸ’»"
path = "~"
startup_command = "ssh alonhearter@alon-mbp"

[[session]]
name = "mini"
path = "~"
startup_command = "ssh hearter@mini"

[[session]]
name = "kielbasa ğŸ¥"
path = "~/personal/kielbasa/"
startup_command = "ssh k"

