[[session]]
name = "scratch"
path = "~"

[[session]]
name = "alon-pc ğŸ–¥ï¸"
path = "~"
startup_command = "ssh alon@alon-pc"

[[session]]
name = "mini"
path = "~"
startup_command = "ssh hearter@mini"

[[session]]
name = "kielbasa ğŸ¥"
path = "~"
startup_command = "ssh k"

